# Generated by Django 5.2.7 on 2025-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
